# Generated by Django 4.2.5 on 2024-04-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationStatus',
            new_name='NotificationType',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.notificationtype', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
