# Generated by Django 4.2.5 on 2024-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_notificationstatus_notificationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=999, verbose_name='Description'),
        ),
    ]
