# Generated by Django 4.2.5 on 2024-04-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercharacteristics',
            options={'verbose_name': "User's Characteristics", 'verbose_name_plural': "User's Characteristics"},
        ),
    ]
