# Generated by Django 4.2.5 on 2024-04-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
