# Generated by Django 4.2.5 on 2024-04-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookgenre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.booktype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Is user paid'),
        ),
    ]
