# Generated by Django 4.2.5 on 2024-04-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
